/** ===== clubData.ts =====
 * 由 tools/import_clubs.ts 從政府開放資料產生，不要手改——重跑一次就會被蓋掉。
 *
 * 來源：全國運動場館資訊（iPlay），運動部
 *       https://data.gov.tw/dataset/22849
 *       政府資料開放授權條款第 1 版
 *
 * 已經篩掉：非網球場、網球練習壁（對牆打，不能約球）、
 *           標示「不開放對外場地租借」的場（租不到，放進來只會害人白跑）。
 *
 * surface / lights / rating / price_per_hour（付費場）都是 null——
 * 開放資料沒有這些欄位。等人工確認過再把值填進來，並把 source 改成 'manual'。
 * courts 一律先當 1 面；真實面數要人工查，它只影響「這個時段還剩幾面」的計算。
 *
 * 開放時間：對得上臺北市體育局訂場系統的才是查證過的，其餘一律是 6–22 的保守預設。
 * booking_url：有值代表這個場在市府線上訂場系統裡。
 *
 * 範圍：臺北市、新北市，開放資料 54 個，
 * 另加 15 個開放資料漏掉、但在臺北市體育局訂場系統裡訂得到的。
 */
import type { Club } from './types.ts'

export const REAL_CLUBS: Club[] = [
  {
    id: 'c-105c6hr', name: "明志國中迎曦廣場(風雨操場)",
    district: "新北市三重區",
    address: "新北市三重區中正北路107號",
    lat: 25.064482, lng: 121.489059,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(9 34% 36%),hsl(14 34% 24%) 55%,hsl(18 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-13ts2co', name: "排球場館",
    district: "新北市三重區",
    address: "新北市三重區中正北路163號",
    lat: 25.069823, lng: 121.479183,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(16 46% 36%),hsl(21 46% 24%) 55%,hsl(25 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-02eb2j8', name: "新北高中網球場",
    district: "新北市三重區",
    address: "新北市三重區三信路1號",
    lat: 25.087455, lng: 121.489794,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(16 40% 36%),hsl(21 40% 24%) 55%,hsl(25 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-17achkz', name: "土城綜合球場-網球場",
    district: "新北市土城區",
    address: "新北市土城區 明德路 清水路 交叉口",
    lat: 24.979221, lng: 121.454374,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(25 34% 36%),hsl(30 34% 24%) 55%,hsl(34 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1e8y3fy', name: "宏國德霖科技學院網球場(館)",
    district: "新北市土城區",
    address: "新北市土城區青雲路380巷1號",
    lat: 24.972287, lng: 121.457537,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(25 46% 36%),hsl(30 46% 24%) 55%,hsl(34 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1mxo36s', name: "中和區錦和運動公園-網球場",
    district: "新北市中和區",
    address: "新北市中和區錦和路350-1號",
    lat: 24.993069, lng: 121.487428,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(12 40% 36%),hsl(17 40% 24%) 55%,hsl(21 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0lmdly4', name: "秀山國民小學網球場(館)",
    district: "新北市中和區",
    address: "新北市中和區立人街2號",
    lat: 24.994499, lng: 121.521792,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(26 52% 36%),hsl(31 52% 24%) 55%,hsl(35 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1x8ba0z', name: "綠寶石網球場（永和河濱）",
    district: "新北市永和區",
    address: "新北市永和區綠寶石公園網球場(新店溪左岸自行車道5.5KM)",
    lat: 25.018155, lng: 121.509411,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: true,
    price_per_hour: 150,
    price_note: "平日每 4 小時 600 元、假日 800 元，未滿 2 小時以半場次計。時段固定兩小時一節：08–10、10–12、13–15、15–17、18–20、20–22。線上申請要先註冊會員，非新北市民也可以註冊。沒有人申請的時段開放現場自由使用。",
    rating: null,
    courts: 1,
    open_hour: 8,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(26 40% 36%),hsl(31 40% 24%) 55%,hsl(35 44% 15%))',
    source: 'manual',
    booking_url: "https://www.hrcm.ntpc.gov.tw/Service/VenueRental/TennisCourtLeaseInst/Detail/綠寶石網球場",
    verified_on: "2026-08-23",
  },
  {
    id: 'c-0wu26dk', name: "華僑高級中學網球場(館)",
    district: "新北市板橋區",
    address: "新北市板橋區大觀路一段32號",
    lat: 25.006955, lng: 121.446251,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(11 34% 36%),hsl(16 34% 24%) 55%,hsl(20 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1swl24q', name: "新月網球場",
    district: "新北市板橋區",
    address: "新北市板橋區新月橋與特二橋間網球場(大漢溪右岸自行車道3.75K",
    lat: 25.024217, lng: 121.449501,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(8 40% 36%),hsl(13 40% 24%) 55%,hsl(17 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0gejqbn', name: "林口高中網球場(館)",
    district: "新北市林口區",
    address: "新北市林口區仁愛路二段173號",
    lat: 25.072976, lng: 121.380043,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(27 52% 36%),hsl(32 52% 24%) 55%,hsl(36 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0fk0mr6', name: "第二運動公園網球場",
    district: "新北市林口區",
    address: "24462新北市林口區民族路205號",
    lat: 25.078024, lng: 121.367834,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(15 46% 36%),hsl(20 46% 24%) 55%,hsl(24 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-06td8b7', name: "臺灣師範大學室外網球場",
    district: "新北市林口區",
    address: "新北市林口區仁愛路一段2號",
    lat: 25.06939, lng: 121.403024,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(20 46% 36%),hsl(25 46% 24%) 55%,hsl(29 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0fkdbyh', name: "文化國小田徑場",
    district: "新北市淡水區",
    address: "新北市淡水區文化里真理街6號",
    lat: 25.174053, lng: 121.437963,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(12 52% 36%),hsl(17 52% 24%) 55%,hsl(21 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0nly2vt', name: "真理大學體育館",
    district: "新北市淡水區",
    address: "新北市淡水區真理街32號",
    lat: 25.176622, lng: 121.434808,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(17 34% 36%),hsl(22 34% 24%) 55%,hsl(26 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0jq1ucq', name: "淡江大學網球場(館)",
    district: "新北市淡水區",
    address: "新北市淡水區英專路151號",
    lat: 25.175254, lng: 121.450027,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(25 40% 36%),hsl(30 40% 24%) 55%,hsl(34 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1yr5xdo', name: "聖約翰科技大學網球場",
    district: "新北市淡水區",
    address: "新北市淡水區淡金路四段499號",
    lat: 25.226727, lng: 121.45088,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(25 52% 36%),hsl(30 52% 24%) 55%,hsl(34 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1yr5xdo', name: "聖約翰科技大學網球場",
    district: "新北市淡水區",
    address: "新北市淡水區淡金路四段499號",
    lat: 25.227421, lng: 121.451535,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(25 52% 36%),hsl(30 52% 24%) 55%,hsl(34 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0uf2fga', name: "景文科技大學網球場(館)",
    district: "新北市新店區",
    address: "新北市新店區安忠路99號",
    lat: 24.951968, lng: 121.509331,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(7 34% 36%),hsl(12 34% 24%) 55%,hsl(16 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1gojbyh', name: "小碧潭網球場（新店河濱）",
    district: "新北市新店區",
    address: "新北市新店區小碧潭公園網球場(新店溪右岸自行車道2.3KM)",
    lat: 24.972744, lng: 121.52728,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: true,
    price_per_hour: 150,
    price_note: "平日每 4 小時 600 元、假日 800 元，未滿 2 小時以半場次計。時段固定兩小時一節：08–10、10–12、13–15、15–17、18–20、20–22。線上申請要先註冊會員，非新北市民也可以註冊。沒有人申請的時段開放現場自由使用。",
    rating: null,
    courts: 1,
    open_hour: 8,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(19 52% 36%),hsl(24 52% 24%) 55%,hsl(28 56% 15%))',
    source: 'manual',
    booking_url: "https://www.hrcm.ntpc.gov.tw/Service/VenueRental/TennisCourtLeaseInst/Detail/小碧潭網球場",
    verified_on: "2026-08-23",
  },
  {
    id: 'c-0yin15m', name: "彭福國小網球場(館)",
    district: "新北市樹林區",
    address: "新北市樹林區忠孝街30號",
    lat: 24.981614, lng: 121.423055,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(27 34% 36%),hsl(32 34% 24%) 55%,hsl(36 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1wbp6yi', name: "樹林體育園區網球場",
    district: "新北市樹林區",
    address: "新北市樹林區水源街81號",
    lat: 24.982203, lng: 121.426806,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(21 40% 36%),hsl(26 40% 24%) 55%,hsl(30 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-12sm4rn', name: "微風運河網球場",
    district: "新北市蘆洲區",
    address: "新北市蘆洲區二重疏洪道微風網球場",
    lat: 25.094315, lng: 121.458111,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(13 34% 36%),hsl(18 34% 24%) 55%,hsl(22 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1vmo0ua', name: "鶯歌國小網球場(館)",
    district: "新北市鶯歌區",
    address: "新北市鶯歌區同慶里尖山埔路106號",
    lat: 24.951175, lng: 121.346612,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(19 46% 36%),hsl(24 46% 24%) 55%,hsl(28 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-007sqo2', name: "百齡河濱公園網球場（社子岸）",
    district: "臺北市士林區",
    address: "臺北市士林區通河東街1及2段堤外",
    lat: 25.088431, lng: 121.514947,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: false,
    price_per_hour: 0,
    price_note: "免費，但仍要在臺北市體育局系統預約（要先註冊會員）。沒有夜間照明，天黑就打不了。",
    rating: null,
    courts: 6,
    open_hour: 8,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(11 34% 36%),hsl(16 34% 24%) 55%,hsl(20 38% 15%))',
    source: 'manual',
    booking_url: "https://vbs.sports.taipei/venues/?K=87",
    verified_on: "2026-08-23",
  },
  {
    id: 'c-0fl7cqi', name: "天壽公園",
    district: "臺北市士林區",
    address: "臺北市士林區中山北路6段405巷右側",
    lat: 25.116907, lng: 121.524491,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(22 34% 36%),hsl(27 34% 24%) 55%,hsl(31 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0l425ko', name: "東吳大學網球場(館)",
    district: "臺北市士林區",
    address: "臺北市士林區臨溪路70號",
    lat: 25.09568, lng: 121.544307,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(17 34% 36%),hsl(22 34% 24%) 55%,hsl(26 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1wml0f7', name: "臺北市天母棒球場",
    district: "臺北市士林區",
    address: "臺北市 士林區 忠誠路二段77號",
    lat: 25.113456, lng: 121.532929,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(27 34% 36%),hsl(32 34% 24%) 55%,hsl(36 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0xywvlw', name: "銘傳大學田徑場",
    district: "臺北市士林區",
    address: "臺北市士林區中山北路五段250號",
    lat: 25.087018, lng: 121.52765,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(6 40% 36%),hsl(11 40% 24%) 55%,hsl(15 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-014c0j5', name: "銘傳大學體育館",
    district: "臺北市士林區",
    address: "臺北市士林區中山北路五段250號",
    lat: 25.085599, lng: 121.533508,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(20 52% 36%),hsl(25 52% 24%) 55%,hsl(29 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1823beb', name: "臺北教育大學網球場",
    district: "臺北市大安區",
    address: "臺北市大安區和平東路二段134號",
    lat: 25.022112, lng: 121.544859,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(8 40% 36%),hsl(13 40% 24%) 55%,hsl(17 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1g2soks', name: "臺灣科技大學網球場(館)",
    district: "臺北市大安區",
    address: "臺北市大安區基隆路四段43號",
    lat: 25.014662, lng: 121.54325,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(11 46% 36%),hsl(16 46% 24%) 55%,hsl(20 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0008o0m', name: "美堤河濱公園",
    district: "臺北市中山區",
    address: "臺北市 中山區 大直橋 至 中山高速公路(金泰段右岸)（基隆河右岸）",
    lat: 25.076679, lng: 121.553367,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null,
    courts: 2,
    open_hour: 8,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(11 52% 36%),hsl(16 52% 24%) 55%,hsl(20 56% 15%))',
    source: 'manual',
    booking_url: "https://vbs.sports.taipei/venues/?K=174",
    verified_on: "2026-08-23",
  },
  {
    id: 'c-0flprbw', name: "新生公園網球場",
    district: "臺北市中山區",
    address: "臺北市中山區新生北路3段105號",
    lat: 25.068495, lng: 121.531745,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(17 46% 36%),hsl(22 46% 24%) 55%,hsl(26 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-187m0ht', name: "臺北市中山區大佳河濱公園",
    district: "臺北市中山區",
    address: "臺北市 中山區 圓山橋下10號水門 大直橋至中山橋(大佳段)（基隆河左岸）",
    lat: 25.074803, lng: 121.535547,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(9 34% 36%),hsl(14 34% 24%) 55%,hsl(18 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-197lw6y', name: "三民國中網球場",
    district: "臺北市內湖區",
    address: "臺北市內湖區湖興里民權東路6段45號",
    lat: 25.069518, lng: 121.584993,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(12 46% 36%),hsl(17 46% 24%) 55%,hsl(21 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1g9ltan', name: "內湖區石潭公園",
    district: "臺北市內湖區",
    address: "臺北市 內湖區 安康路25巷",
    lat: 25.063694, lng: 121.592651,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(26 46% 36%),hsl(31 46% 24%) 55%,hsl(35 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0knqvfe', name: "西湖國中網球場",
    district: "臺北市內湖區",
    address: "臺北市內湖區西湖里環山路1段27號",
    lat: 25.086114, lng: 121.565797,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(13 40% 36%),hsl(18 40% 24%) 55%,hsl(22 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-15j77uu', name: "煙波庭公園",
    district: "臺北市內湖區",
    address: "臺北市 內湖區 大湖街131巷18弄61號",
    lat: 25.086504, lng: 121.599029,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(11 46% 36%),hsl(16 46% 24%) 55%,hsl(20 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1adteb4', name: "瑞湖公園",
    district: "臺北市內湖區",
    address: "臺北市 內湖區 民權東路六段15巷及瑞湖街交接口",
    lat: 25.069429, lng: 121.577228,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(8 46% 36%),hsl(13 46% 24%) 55%,hsl(17 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0iow7ho', name: "臺北市網球中心",
    district: "臺北市內湖區",
    address: "臺北市內湖區民權東路6段208號",
    lat: 25.067446, lng: 121.596648,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: true,
    price_per_hour: 300,
    price_note: "室外離峰 300、尖峰 600（平日 17–19 時、假日 13–19 時），夜間另收燈光費 200；室內全日 2000。室外開放到 19:00，室內到 22:00。尖峰時段一次要訂兩小時，離峰可訂一小時。",
    rating: null,
    courts: 10,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(27 40% 36%),hsl(32 40% 24%) 55%,hsl(36 44% 15%))',
    source: 'manual',
    booking_url: "https://www.tsc.taipei/場館介紹/室外網球場outdoor/",
    verified_on: "2026-08-23",
  },
  {
    id: 'c-1q5cdaz', name: "萬有二號公園",
    district: "臺北市文山區",
    address: "臺北市 文山區 景隆街19巷4-2號",
    lat: 25.00073, lng: 121.541635,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(21 46% 36%),hsl(26 46% 24%) 55%,hsl(30 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-06ex74s', name: "文林國小田徑場",
    district: "臺北市北投區",
    address: "臺北市北投區建民里文林北路155號",
    lat: 25.105675, lng: 121.51395,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(16 34% 36%),hsl(21 34% 24%) 55%,hsl(25 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0uo7bm9', name: "明德國中田徑場",
    district: "臺北市北投區",
    address: "臺北市北投區建民里明德路50號",
    lat: 25.107994, lng: 121.518697,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(8 34% 36%),hsl(13 34% 24%) 55%,hsl(17 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1p4fpa5', name: "逸仙國小網球場、籃球場、躲避球場、樂樂棒球場",
    district: "臺北市北投區",
    address: "臺北市北投區中心里新民路2號",
    lat: 25.138165, lng: 121.50557,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(25 46% 36%),hsl(30 46% 24%) 55%,hsl(34 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1psnhgm', name: "陽明大學山下球場",
    district: "臺北市北投區",
    address: "臺北市北投區立農街二段155號",
    lat: 25.119784, lng: 121.51372,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(11 52% 36%),hsl(16 52% 24%) 55%,hsl(20 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-02qp7af', name: "陽明大學山頂網球場",
    district: "臺北市北投區",
    address: "臺北市北投區立農街二段155號",
    lat: 25.124421, lng: 121.513816,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(22 40% 36%),hsl(27 40% 24%) 55%,hsl(31 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1qsa9ed', name: "臺北藝術大學網球場(館)",
    district: "臺北市北投區",
    address: "臺北市北投區學園路1號",
    lat: 25.136524, lng: 121.47465,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(24 34% 36%),hsl(29 34% 24%) 55%,hsl(33 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-11ojnba', name: "臺北網球場",
    district: "臺北市松山區",
    address: "臺北市 松山區 南京東路4段6號",
    lat: 25.051337, lng: 121.551334,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(16 34% 36%),hsl(21 34% 24%) 55%,hsl(25 38% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-00jd8gj', name: "臺北醫學大學網球場(館)",
    district: "臺北市信義區",
    address: "臺北市信義區吳興街250號",
    lat: 25.026049, lng: 121.561403,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: null,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(8 52% 36%),hsl(13 52% 24%) 55%,hsl(17 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1asmr0i', name: "中研公園",
    district: "臺北市南港區",
    address: "臺北市 南港區 研究路2段12巷58弄",
    lat: 25.046836, lng: 121.613449,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(17 52% 36%),hsl(22 52% 24%) 55%,hsl(26 56% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0z1pvmg', name: "中華科技大學操場",
    district: "臺北市南港區",
    address: "臺北市南港區研究院路三段245號",
    lat: 25.032699, lng: 121.610847,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(27 46% 36%),hsl(32 46% 24%) 55%,hsl(36 50% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-1bvbons', name: "玉成公園",
    district: "臺北市南港區",
    address: "臺北市 南港區 中坡南路55號",
    lat: 25.042491, lng: 121.585071,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: null,
    price_per_hour: 0,
    price_note: null,
    rating: null,
    courts: 1,
    open_hour: 6,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(19 40% 36%),hsl(24 40% 24%) 55%,hsl(28 44% 15%))',
    source: 'opendata',
    booking_url: null,
    verified_on: null,
  },
  {
    id: 'c-0rbgz6v', name: "南港公園",
    district: "臺北市南港區",
    address: "臺北市 南港區 東新街170號",
    lat: 25.045146, lng: 121.591799,
    surface: null,
    // 名稱帶「室內」的才敢說是室內；沒寫的一律當戶外，寧可少說也不要說錯
    indoor: false,
    lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null,
    courts: 1,
    open_hour: 8,
    close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(20 46% 36%),hsl(25 46% 24%) 55%,hsl(29 50% 15%))',
    source: 'manual',
    booking_url: "https://vbs.sports.taipei/venues/?K=609",
    verified_on: "2026-08-23",
  },
  {
    id: 'c-vbs-341', name: "大佳河濱運動公園網球場",
    district: "臺北市中山區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "大佳河濱運動公園網球場",
    lat: 25.074849, lng: 121.531508,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 2,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(22 46% 36%),hsl(27 46% 24%) 55%,hsl(31 50% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=341',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-266', name: "中正河濱公園中正網球場",
    district: "臺北市中正區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "中正河濱公園中正網球場",
    lat: 25.023453078713725, lng: 121.51428624222645,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 3,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(10 40% 36%),hsl(15 40% 24%) 55%,hsl(19 44% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=266',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-305', name: "古亭河濱公園網球場",
    district: "臺北市中正區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "古亭河濱公園網球場",
    lat: 25.019024, lng: 121.522689,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 2,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(17 46% 36%),hsl(22 46% 24%) 55%,hsl(26 50% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=305',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-201', name: "彩虹河濱公園網球場",
    district: "臺北市內湖區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "彩虹河濱公園網球場",
    lat: 25.062687, lng: 121.571815,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 9,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(26 46% 36%),hsl(31 46% 24%) 55%,hsl(35 50% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=201',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-312', name: "成美右岸河濱公園網球場",
    district: "臺北市內湖區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "成美右岸河濱公園網球場",
    lat: 25.05581, lng: 121.586324,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 1,
    open_hour: 8, close_hour: 17,
    photo: 'linear-gradient(150deg,hsl(22 46% 36%),hsl(27 46% 24%) 55%,hsl(31 50% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=312',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-604', name: "碧湖公園網球場",
    district: "臺北市內湖區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "碧湖公園網球場",
    lat: 25.081903, lng: 121.583775,
    surface: null, indoor: false, lights: false,
    price_per_hour: 0,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 1,
    open_hour: 8, close_hour: 17,
    photo: 'linear-gradient(150deg,hsl(23 40% 36%),hsl(28 40% 24%) 55%,hsl(32 44% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=604',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-342', name: "天母運動場區網球場",
    district: "臺北市士林區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "天母運動場區網球場",
    lat: 25.113514, lng: 121.535606,
    surface: null, indoor: false, lights: true,
    price_per_hour: null,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 6,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(23 52% 36%),hsl(28 52% 24%) 55%,hsl(32 56% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=342',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-324', name: "延平河濱公園網球場",
    district: "臺北市大同區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "延平河濱公園網球場",
    lat: 25.054497, lng: 121.506679,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 1,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(9 52% 36%),hsl(14 52% 24%) 55%,hsl(18 56% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=324',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-489', name: "景美河濱公園網球場",
    district: "臺北市文山區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "景美河濱公園網球場",
    lat: 24.991534, lng: 121.536613,
    surface: null, indoor: false, lights: false,
    price_per_hour: 0,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 1,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(26 46% 36%),hsl(31 46% 24%) 55%,hsl(35 50% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=489',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-352', name: "溪洲[福和]河濱公園網球場",
    district: "臺北市文山區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "溪洲[福和]河濱公園網球場",
    lat: 25.000052, lng: 121.534781,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 1,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(8 46% 36%),hsl(13 46% 24%) 55%,hsl(17 50% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=352',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-253', name: "道南河濱公園網球場1-2",
    district: "臺北市文山區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "道南河濱公園網球場1-2",
    lat: 24.993917, lng: 121.57182,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 1,
    open_hour: 8, close_hour: 17,
    photo: 'linear-gradient(150deg,hsl(22 52% 36%),hsl(27 52% 24%) 55%,hsl(31 56% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=253',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-425', name: "道南河濱公園網球場4-6",
    district: "臺北市文山區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "道南河濱公園網球場4-6",
    lat: 24.9828, lng: 121.570274,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 2,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(20 34% 36%),hsl(25 34% 24%) 55%,hsl(29 38% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=425',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-320', name: "民權公園網球場",
    district: "臺北市松山區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "民權公園網球場",
    lat: 25.061584, lng: 121.55929,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 2,
    open_hour: 6, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(28 52% 36%),hsl(33 52% 24%) 55%,hsl(37 56% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=320',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-239', name: "華中河濱公園網球場",
    district: "臺北市萬華區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "華中河濱公園網球場",
    lat: 25.017174, lng: 121.491658,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 7,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(12 52% 36%),hsl(17 52% 24%) 55%,hsl(21 56% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=239',
    verified_on: '2026-08-23',
  },
  {
    id: 'c-vbs-210', name: "雙園河濱公園網球場",
    district: "臺北市萬華區",
    // 體育局場館頁沒有門牌地址，河濱球場本來也沒有；用場館名稱當地址欄的內容，
    // 畫面上至少講得出這是哪裡，導航靠的是座標
    address: "雙園河濱公園網球場",
    lat: 25.034276, lng: 121.488169,
    surface: null, indoor: false, lights: true,
    price_per_hour: 140,
    price_note: "臺北市體育局線上預約，要先註冊會員。未開放線上預約的面只供現場民眾輪流使用。",
    rating: null, courts: 4,
    open_hour: 8, close_hour: 22,
    photo: 'linear-gradient(150deg,hsl(10 34% 36%),hsl(15 34% 24%) 55%,hsl(19 38% 15%))',
    source: 'manual',
    booking_url: 'https://vbs.sports.taipei/venues/?K=210',
    verified_on: '2026-08-23',
  },
]
